"""Hypothesis-driven reasoning interfaces.

Minimal extraction from HEXSTRIKE9.9 reasoning_interfaces.py (794 lines)
down to the essential types needed for Phase 2.
"""

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class HypothesisSource(str, Enum):
    """Origin of a hypothesis."""

    LLM = "llm"
    RAG = "rag"
    PATTERN = "pattern"
    RULE = "rule"


class HypothesisStatus(str, Enum):
    """Lifecycle status of a hypothesis."""

    PENDING = "pending"
    TESTING = "testing"
    VERIFIED = "verified"
    REFUTED = "refuted"
    ADAPTED = "adapted"


@dataclass
class AttackHypothesis:
    """A testable attack hypothesis.

    Generated by the reasoning engine and converted to AttackTree nodes
    for execution and verification.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    description: str = ""
    preconditions: list[str] = field(default_factory=list)
    expected_outcome: str = ""
    verification_method: str = ""  # Shell command to verify
    confidence: float = 0.5
    source: HypothesisSource = HypothesisSource.RULE
    status: HypothesisStatus = HypothesisStatus.PENDING
    reasoning: str = ""
    parent_hypothesis_id: str | None = None  # Adaptation chain tracking

    def __post_init__(self) -> None:
        """Clamp confidence to valid [0.0, 1.0] range."""
        self.confidence = max(0.0, min(1.0, float(self.confidence)))


@dataclass
class VerificationResult:
    """Result of hypothesis verification against tool output."""

    hypothesis_id: str
    verified: bool
    confidence_delta: float = 0.0
    actual_outcome: str = ""
    evidence: dict[str, Any] = field(default_factory=dict)
    next_actions: list[str] = field(default_factory=list)


class ReasoningEngine(ABC):
    """Abstract interface for hypothesis-driven reasoning."""

    @abstractmethod
    def generate_hypotheses(
        self, context: dict[str, Any]
    ) -> list[AttackHypothesis]:
        """Generate attack hypotheses from current context."""
        ...

    @abstractmethod
    def select_hypothesis(
        self, hypotheses: list[AttackHypothesis]
    ) -> AttackHypothesis:
        """Select the most promising hypothesis."""
        ...

    @abstractmethod
    def verify_hypothesis(
        self, hypothesis: AttackHypothesis, result: str
    ) -> VerificationResult:
        """Verify a hypothesis against execution results."""
        ...
